// Automatically generated by MockGen. DO NOT EDIT!
// Source: gopkg.in/alecthomas/kingpin.v2 (interfaces: Settings)

package configstring

import (
	gomock "github.com/golang/mock/gomock"
	kingpin_v2 "gopkg.in/alecthomas/kingpin.v2"
)

// Mock of Settings interface
type MockSettings struct {
	ctrl     *gomock.Controller
	recorder *_MockSettingsRecorder
}

// Recorder for MockSettings (not exported)
type _MockSettingsRecorder struct {
	mock *MockSettings
}

func NewMockSettings(ctrl *gomock.Controller) *MockSettings {
	mock := &MockSettings{ctrl: ctrl}
	mock.recorder = &_MockSettingsRecorder{mock}
	return mock
}

func (_m *MockSettings) EXPECT() *_MockSettingsRecorder {
	return _m.recorder
}

func (_m *MockSettings) SetValue(_param0 kingpin_v2.Value) {
	_m.ctrl.Call(_m, "SetValue", _param0)
}

func (_mr *_MockSettingsRecorder) SetValue(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetValue", arg0)
}
